### ISSUE TITLE
cli: update 'popper ci' to make pipeline native to jenkins

### ISSUE THREAD

**Issue by ivotron** [getpopper/popper#494]
this allows to visualize the popper stages in their UI

**Comment by JayjeetAtGithub** [comment]
Hi @ivotron 
Can you please explain issues #492, #493, #494 briefly so that we can include those in our proposals ?

> this allows to visualize the popper stages in their UI

What does UI refer to here ?

**Comment by ivotron** [comment]
@JayjeetAtGithub this refers to jenkins' [pipeline visualizer](https://wiki.jenkins.io/display/JENKINS/Pipeline+Stage+View+Plugin). Right now, the jenkinsfile that gets generated contains only one stage. We can modify it so that we generate every jenkins pipeline stage for each action in the workflow.

**Comment by JayjeetAtGithub** [comment]
@ivotron This means that for a build action we would generate a jenkins build stage and so on and so forth right? Means basically a jenkins port of our workflow would make some sense.
