### ISSUE TITLE
cli: show colorized output from steps

### ISSUE THREAD

**Issue by ivotron** [getpopper/popper#627]
currently, if a step generates colored output, `popper run` is not showing it

**Comment by akashrajr1** [comment]
@ivotron how do I reproduce the required colors for the example? 
And if the goal is to use colors, we can also set them through `popper` so that even if an example doesn't produce colors, `popper` can do that on its own.

**Comment by ivotron** [comment]
thanks a lot for looking into this @akashrajr1! To produce colors out of a container:

```bash
docker run --rm -t -e "TERM=xterm-256color" alpine:3.9 ls -l
```

so it might be a matter of enabling `tty` when `popper run` creates containers.
