### ISSUE TITLE
cli: support concurrent execution in vagrant runtime

### ISSUE THREAD

**Issue by JayjeetAtGithub** [getpopper/popper#745]
Add the support of running 2 or more workflows concurrently in Vagrant runtime which is currently not supported. 

**Current Scenario:**

Currently, Popper is configured to spawn a new VM for every workflow.  Also, the docker daemon inside every VM listens on `tcp://0.0.0.0:2375`. When 2 or more workflows are executed concurrently, 2 different VM's are spawned with the docker daemons inside them trying to listen on the same port. Hence, it results in an error or abnormal behaviors.

**Possible Solution:**

We can change the logic to create a generalized VM at the beginning of any workflow, so essentially we would no more spawn new VM's for different workflows. Now, If two or more workflows are run concurrently, any one of them will spawn the generalized VM and others would check if the VM is up and use that for their execution also.

Please feel free to suggest other solutions.

**Comment by ivotron** [comment]
vagrant runner was dropped. We can reopen this if the vagrant functionality is requested
