### ISSUE TITLE
cli: unit test the click based CLI interface

### ISSUE THREAD

**Issue by JayjeetAtGithub** [getpopper/popper#761]
Interested? Have a look at this. http://click.palletsprojects.com/en/7.x/testing/

**Comment by vipulchhabra99** [comment]
Hi @JayjeetAtGithub, Can you give some more context on what exactly needs to be done in the issue.

**Comment by vipulchhabra99** [comment]
HI @JayjeetAtGithub, I am interested in working on this issue.

**Comment by JayjeetAtGithub** [comment]
@vipulchhabra99 Basically, we want to increase our test coverage by testing the CLI functionality. You can first check whether writing these tests increases the test coverage or not. I am not quite sure. If it does, we can test all the commands and flag as unit tests and just check whether the return codes are 0 or not.

**Comment by vipulchhabra99** [comment]
Ok, great @JayjeetAtGithub, I can write creating test cases for one or 2 commands if that works out, I can add more.

**Comment by vipulchhabra99** [comment]
HI, @JayjeetAtGithub I was working on this. I am writing for cmd_ci command I saw that it requires ctx variable bus hasn't been used anywhere in the definition of the function. I created a dummy click.context() variable and assigned the value to it but it shows exit code 1 during testing. Do I need to specify some special value or there can be the case of missing flags?

**Comment by ivotron** [comment]
@vipulchhabra99 please take a look at here and let us know if you have any question https://stackoverflow.com/a/40443542

**Comment by ivotron** [comment]
fixed in #807 and #810
