### ISSUE TITLE
cli: add 'help' command

### ISSUE THREAD

**Issue by ivotron** [getpopper/popper#787]
add a `help` command with the following spec:

```bash
popper help [subcommand]
```

When `[subcommand]` is not given, it is equivalent to the current `popper --help`. When the `[subcommand]` argument is given, it is equivalent to `popper subcommand --help`.

For this, the help message doesn't have to be recreated, but instead we can invoke Click's [`get_help()`](http://click.palletsprojects.com/en/7.x/api/#click.Command.get_help) function of each subcommand.

**Comment by fsr313** [comment]
I would like to work in this issue

**Comment by ivotron** [comment]
Please go ahead. Let us know if you have any questions
