### ISSUE TITLE
cli: check for the presence of required executables

### ISSUE THREAD

**Issue by JayjeetAtGithub** [getpopper/popper#812]
The [`assert_executable_exists(cmd)`](https://github.com/systemslab/popper/blob/master/cli/popper/utils.py#L55) function checks for the presence of an executable in the environment where the workflow is executed.

So, we can utilize this function to check for the presence of the required binaries/executables through the `__init__()` method(constructor) of the concerned runner classes, like [`runner_slurm.SlurmRunner`](https://github.com/systemslab/popper/blob/master/cli/popper/runner_slurm.py#L12), etc defined in [`runner_host.py`](https://github.com/systemslab/popper/blob/master/cli/popper/runner_host.py) and [`runner_slurm.py`](https://github.com/systemslab/popper/blob/master/cli/popper/runner_slurm.py). This would block a runner from getting initialized and fail if it does not meet its required software dependencies.

For example, we need to check for `sbatch` executable in `runner_slurm.SlurmRunner`, `singularity` executable in `runner_host.SingularityRunner`,  `podman` in `runner_host.PodmanRunner`, etc.

**Comment by abbycriswell** [comment]
Hello again! My teammate and I also commented on issue #913. We would also like to work on this issue.

**Comment by JayjeetAtGithub** [comment]
Hi @abbycriswell. Thanks a lot for looking into this issue. Please go ahead. Feel free to ask any questions you might have. You can start by looking into the [contribution guidelines](https://github.com/getpopper/popper/blob/master/CONTRIBUTING.md) and the [development environment setup](https://github.com/getpopper/popper/blob/master/docs/installation.md#development-setup) guides. Also, feel free to join our slack channel ([join here](https://join.slack.com/t/getpopper/shared_invite/zt-dtn0se2s-c50myMHNpeoikQXDeNbPew)) for any discussion regarding the issue.
