### ISSUE TITLE
cli: add GIT_TAG as an environment variable

### ISSUE THREAD

**Issue by ivotron** [getpopper/popper#834]
Currently, Popper makes the `GIT_COMMIT`, `GIT_BRANCH` and `GIT_SHA_SHORT` environment variables available to each step when a workflow runs inside a git project folder. For this issue, we will add support for defining a `GIT_TAG` variable that contains the tag of the current commit, if any.

For this, we can make use of the [`git describe`](https://git-scm.com/docs/git-describe) functionality via GitPython, similarly to the way it's done for obtaining the current commit (see [here](https://github.com/systemslab/popper/blob/2885e16/cli/popper/scm.py#L161)).

**Comment by MJVNOR** [comment]
can I have this?

**Comment by JayjeetAtGithub** [comment]
> can I have this?

Sure. Go ahead.

**Comment by MJVNOR** [comment]
Thanks

**Comment by DanielOsunaV** [comment]
Hi @MJVNOR I was already tackling this issue :'( do you have much advanced work?

**Comment by MJVNOR** [comment]
No

**Comment by DanielOsunaV** [comment]
I'll be so glad if you let me finish this by myself

**Comment by MJVNOR** [comment]
sure, no problem
