### ISSUE TITLE
cli: Reuse Flag is not working as expected

### ISSUE THREAD

**Issue by vipulchhabra99** [getpopper/popper#837]
`--reuse `flag was earlier implemented but recently after the major Refactoring of the Codebase, it stopped working in an expected way. 
**Current State**: on passing reuse flag It re-runs the same workflow and ignores the new commands or arguments passed in the updated workflow.

**Comment by ivotron** [comment]
sorry @vipulchhabra99 , I didn't realize we already had  #694 .
