### ISSUE TITLE
cli: add GIT_REMOTE_ORIGIN_URL variable

### ISSUE THREAD

**Issue by ivotron** [getpopper/popper#852]
Currently, Popper makes the `GIT_COMMIT`, `GIT_BRANCH` and `GIT_SHA_SHORT` variables available for steps whenever `popper run` is executed inside a git repository. For this issue, we will also add support for defining a `GIT_REMOTE_ORIGIN_URL` variable that contains the URL of the remote from which the repository was cloned from.

For this, we can make use of the `git config --get remote.origin.url` functionality via GitPython (`repo.remotes.origin.url` property of a `git.Repo` object), so that there is a new `get_remote_origin_url()` function in the [`src/popper/scm.py`](https://github.com/getpopper/popper/blob/master/src/popper/scm.py)

We can also add tests for this on the [`src/test/test_scm.py`](https://github.com/getpopper/popper/blob/master/src/test/test_scm.py) file.

**Comment by DanielOsunaV** [comment]
Good afternoon, im willing to contribute on this issue, I'm not an expert at python but I see that [src/popper/scm.py](https://github.com/getpopper/popper/blob/master/cli/test/test_scm.py) already have a `get_remote_url`, so the issue is already solved with it, or ¿you want a new variable talking about `GIT_REMOTE_ORIGIN_URL` ?

**Comment by ivotron** [comment]
thanks for looking at this @DanielOsunaV! You're right, that is already available, so the only missing piece would be to add a call to that function [here](https://github.com/getpopper/popper/blob/master/src/popper/runner.py#L222), and update the [existing tests](https://github.com/getpopper/popper/blob/master/src/test/test_runner.py#L127).

You could also take a stab at adding support for a `GIT_TAG` variable (#834) 😃  . This would actually need a new function.

**Comment by DanielOsunaV** [comment]
Thanks for answer @ivotron I'll take this issue today if you're okay with it and I will also see the support for a GIT_TAG variable to check what can I do there 😄 .
