### ISSUE TITLE
example: add a continuous deployment (CD) workflow using terraform

### ISSUE THREAD

**Issue by ivotron** [getpopper/popper#865]
add a new `examples/cd/` folder, and then create  `examples/cd/terraform.yml` that exemplifies how to run terraform in a workflow, as described [here](https://documentation.codeship.com/pro/continuous-deployment/hashicorp-terraform/#steps-configuration). The image used in the workflow can be the [official one](https://hub.docker.com/r/hashicorp/terraform/)

**Comment by RITESG** [comment]
Cd tensorflow

**Comment by VD44** [comment]
In addition to #929, I will begin work on this as well.
