### ISSUE TITLE
cli: add support for running on remote docker hosts

### ISSUE THREAD

**Issue by ivotron** [getpopper/popper#871]
Popper can run workflows on remote docker hosts by use of docker-py's support for the `DOCKER_HOST` variable. We added a commit for this but had to revert it in https://github.com/getpopper/popper/commit/07f911bb596e416229f7b9d2dadc96719fa77575 since the [`src/Dockerfile`](./src/Dockerfile) doesn't build correctly when `paramiko` is added as a dependency. This `Dockerfile` is executed in the [`.popper.yml`](./.popper.yml) pipeline that uploads images to dockerhub (which in turn gets invoked from [`.travis.yml`](./.travis.yml)).
 
For this issue we'll track the changes needed to be done to the `Dockerfile` so that paramiko installs properly.

**Comment by CarterB-UT** [comment]
Can me and a group of other UT students tentatively claim this issue for now? We've also asked after some other tasks.

**Comment by ivotron** [comment]
yes, please go ahead! Let us know if you have any question

**Comment by rishiUT** [comment]
We have successfully made changes to the dockerfile such that the install runs successfully, even when paramiko is added as a dependency. Is there anything else we can do to add support for remote docker hosts, or is the paramiko install sufficient?

**Comment by ivotron** [comment]
cool, that's great! That would be sufficient for this issue
