### ISSUE TITLE
cli: Add line profiler to check timing of each line of code

### ISSUE THREAD

**Issue by edeediong** [getpopper/popper#873]
I believe this tool [line profiler](https://github.com/rkern/line_profiler) to optimize the performance of Popper. Though it's archived it can be still be used to test each line of code to still how long it executes. 

Also, can we introduce regression testing and load testing to Popper? It could help us in analysing the speed of Popper and properly prepare for downtimes.

**Comment by ivotron** [comment]
we could use flame graphs: https://github.com/evanhempel/python-flamegraph
