### ISSUE TITLE
cli: Ensure regression tests is performed on Popper

### ISSUE THREAD

**Issue by edeediong** [getpopper/popper#877]
It will really help to monitor performance issues of this tool if regression tests can be performed. However, can I get a list of possible tests that need to be performed before regression is done?

**Comment by ivotron** [comment]
thanks Eddie, this is a great idea. One test could be to run `popper run --dry run` and see how long it takes. Do this repeatedly and get an average with some tolerance for variability, and use this as the basis for comparison. The issue is that we need to run these tests on the same platform always, otherwise the numbers might not be comparable between runs

**Comment by edeediong** [comment]
Oh, it's nice to know popper has an inbuilt feature to know how long it takes. So I'm not totally sure but if this was written with Golang, I believe we would've used Go tests to be able to benchmark how long popper loads. So two things yeah:
1. What's your idea for the kinda system/platform that can be used to run this test? I thought of Weave but I'm not exactly familiar with their kinda services.
2. Also, when performing performance testing, would the number of steps in a workflow determine the speed?

**Comment by ivotron** [comment]
> it's nice to know popper has an inbuilt feature to know how long it takes

that's not available yet (see #869 ). However, we can create a test by having a fixed `wf.yml` file and then doing:

```bash
time popper run -f wf.yml
```

we can repeat the above X number of times and show the variability.

> What's your idea for the kinda system/platform that can be used to run this test? 

we can make use of a baremetal-as-a-service platform like packet.net or scaleway 

> when performing performance testing, would the number of steps in a workflow determine the speed?

yeah, so we need to have some fixed workflow and use that always
