### ISSUE TITLE
cli: add github,survey links to help message

### ISSUE THREAD

**Issue by ivotron** [getpopper/popper#883]
add a splash screen at a random that invites the users to fill out a survey, add a star on github, join slack, etc. This will also include the option so users specify they don't want to see the splash screen at all in the future.

**Comment by CarterB-UT** [comment]
Hey! If it's okay, my student group could also do this issue since it is so close to #884.

**Comment by CarterB-UT** [comment]
Hey. So we were just wondering if you had any recommendations about how to preserve the decision to skip this screen between runs of popper. We were looking at config.py and were contemplating adding a simple variable to that but we were uncertain of config works on the scale of popper as a whole or if those configs are individual to each box you use with popper. If config.py is box-specific where else could we look for across-run durability? Thanks!

**Comment by ivotron** [comment]
hi @CarterB-UT, I was thinking about the UX aspect of this feature, as well as what you asked (how to persist a config) and was wondering if it would make more sense to show this info as part of the `popper help` message instead. This would simplify the implementation, and would also avoid annoying users. What do you think?

**Comment by CarterB-UT** [comment]
Yeah, I was talking about that with the others I am working with and we see how that'd be better design. Randomly inserting it after a normal run would probably result in it being unintentionally ignored more often and putting it under help would get the newer users who are more likely to have not already done those things. 

Just for clarity @ivotron , are you still wanting this print to be optional with the ability to turn it off? And from your response am I getting that configs right now are more box-focused as opposed to for popper across runs?

**Comment by ivotron** [comment]
I was thinking of showing it always as part of the output of `popper help`, so that there is no need to deal with the logic of randomly showing it or storing a "don't show this again" preference.

> putting it under help would get the newer users who are more likely to have not already done those things.

that's true. So what about showing it as part of the output of `popper help` but randomly? For example:

```python
import random

if random.randint(0,9) == 0:
    # show
```

> And from your response am I getting that configs right now are more box-focused as opposed to for popper across runs?

a box can be persisted ([see here](https://github.com/cdgriffith/Box/wiki/Converters) for the full list of converters) but we'd need to deal with where to persist the answer (local folder, home folder, `/var`, etc.), and then with the issue of only having access to the current folder when running popper in docker, which is the preferred way.

So showing as part of `popper help`, either randomly or always would simplify things significantly.

what do y'all think?

**Comment by rishiUT** [comment]
We completely agree! If we don't need to store a "show again preference" it will also simplify the user experience, as they won't have to deal with an unexpected prompt where they only expected printed text and immediate access to the command line.

We have currently removed the random aspect of the splash screen, but it would not be difficult to add it once again. As a user I personally prefer consistency, but this varies from user to user and we will absolutely defer to your judgement in this decision.

Since this is a splash screen, are there any special visual effects you would like us to add, such as ascii art? This is current output of the help message:
![image](https://user-images.githubusercontent.com/47756598/100164238-126f3600-2e7d-11eb-907e-b4e66a122657.png)

**Comment by ivotron** [comment]
> Since this is a splash screen, are there any special visual effects you would like us to add, such as ascii art?

I think this issue evolved from the initial goal of having a splash screen to modifying the help message content. So I think it is great as you have it. I've shortened the slack link: https://bit.ly/join-popper-slack . And another one for the form: https://bit.ly/popper-survey
