### ISSUE TITLE
cli: add post-install message to invite users to fill out survey

### ISSUE THREAD

**Issue by ivotron** [getpopper/popper#884]
Add a message that gets displayed as part of the installer to invite users to fill out survey, join slack, star github, etc.

**Comment by CarterB-UT** [comment]
Hello again! Can I and the same group of UT students also take a whack at this? If we did this we could likely also do issue #883 to round things out.

**Comment by rishiUT** [comment]
Hi there! Regarding the survey you mentioned in this issue and in #883, would you like us to make a survey or is there an existing survey we should use? If we should make a survey, are there any specific questions you'd like us to include?

**Comment by ivotron** [comment]
hi! Thank you so much for working on this issue! This is the link: https://forms.gle/h1geK98fDboEhMXL6 . It is currently WIP but I'll update it in a week or so.
