### ISSUE TITLE
Singularity not working through dockerized `popper`

### ISSUE THREAD

**Issue by wtraylor** [getpopper/popper#898]
# Steps to reproduce
```bash
# Create a dummy project
mkdir project
cd project
# Download the popper script
curl -sSfL https://raw.githubusercontent.com/getpopper/popper/master/install.sh | sh
chmod +x popper
./popper scaffold
# Try to run workflow with singularity
./popper run -f wf.yml --engine singularity
```
Error message:
```
[popper] Cloning step repositories
[popper] - https://github.com/popperized/bin@master
[1] singularity build popper_1_1970273b.sif /home/living/.cache/popper/1970273b/github.com/popperized/bin/sh
ERROR: [Errno 2] No such file or directory: 'sudo': 'sudo'
```
Version: current `master`, commit 227bfee

# The Problem
Singularity and `sudo` are not installed in the Docker container that is running `popper`.

# Tried Solutions
Install Singularity in Popper’s Alpine-based Docker image (`scr/Dockerfile`):
```dockerfile
FROM python:3.7.7-alpine3.12

COPY . /popper

RUN apk --no-cache add git && \
    pip install --no-cache-dir /popper && \
    rm -r /popper

# NEW: Install Singularity from the testing repository.
RUN echo http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories && \
    apk update && \
    apk add sudo singularity

ENTRYPOINT ["popper"]
```

However, with that installed I get an error about `mksquashfs`:
```
$ popper run -f wf.yml -e singularity
[popper] Cloning step repositories
[popper] - https://github.com/popperized/bin@master
[1] singularity build popper_1_1970273b.sif /home/living/.cache/popper/1970273b/github.com/popperized/bin/sh
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
FATAL:   Unable to create build: while searching for mksquashfs: exec: "mksquashfs": executable file not found in $PATH
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
FATAL:   Unable to create build: while searching for mksquashfs: exec: "mksquashfs": executable file not found in $PATH
[1] singularity run popper_1_1970273b.sif ['ls']
FATAL:   could not open image /home/living/.cache/popper/singularity/1970273b/popper_1_1970273b.sif: failed to retrieve path for /home/living/.cache/popper/singularity/1970273b/popper_1_1970273b.sif: lstat /home/living/.cache/popper/singularity/1970273b/popper_1_1970273b.sif: no such file or directory
ERROR: Step '1' failed ('255') !
```
This error persists even if I install `squashfs-tools` in the Dockerfile above (`apk add sudo singularity squashfs-tools`).

Now, that `mksquashfs` cannot be found is because of the environment variables. If I delete the argument `--env-file /tmp/.envfile` from `docker run ...` in the `docker` script, it works. On Alpine Linux it is under `/sbin/mksquasfs`, but `/sbin` is not in the `$PATH` of my personal system (Archlinux).

However, even with that fix I can’t run `popper run -f wf.yml -e singularity` because of this error message:
```
$ popper run -f wf.yml -e singularity
[popper] Cloning step repositories
[popper] - https://github.com/popperized/bin@master
[1] singularity build popper_1_1970273b.sif /root/.cache/popper/1970273b/github.com/popperized/bin/sh
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
ERROR  : Failed to unshare root file system: Operation not permitted
FATAL:   While performing build: while running engine: while running /usr/libexec/singularity/bin/starter: exit status 1
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
ERROR  : Failed to unshare root file system: Operation not permitted
FATAL:   While performing build: while running engine: while running /usr/libexec/singularity/bin/starter: exit status 1
[1] singularity run popper_1_1970273b.sif ['ls']
FATAL:   could not open image /root/.cache/popper/singularity/1970273b/popper_1_1970273b.sif: failed to retrieve path for /root/.cache/popper/singularity/1970273b/popper_1_1970273b.sif: lstat /root/.cache/popper/singularity/1970273b/popper_1_1970273b.sif: no such file or directory
ERROR: Step '1' failed ('255') !
```

# Conlusions
We have some compounded errors here:
1. Singularity and `sudo` should be installed in the Docker container running `popper`.
2. Overwriting that container’s `$PATH` with the host system’s environment variables might not be a good idea in general. It leads to errors that are hard to track. The containerized Alpine system must retain its own `$PATH`.
3. Some errors with `unshare root file system`, which I don’t understand. Any ideas?

**Comment by wtraylor** [comment]
Oh, just now I am seeing that Singularity is not supposed to be supported by Popper installed through `install.sh`:
> The installer script is the preferred method if Docker is the container engine available in your system, as in this case Popper runs in Docker itself. For other container engines such as Singularity, you will need to install the Python Package (see "Install in a Virtualenv" section). 

Okay, then I vote for a meaningful error message.

**Comment by wtraylor** [comment]
I opened a separate issue for `$PATH`: #900.

Once there is an error message for Singularity, this issue can be closed for my sake.

**Comment by ivotron** [comment]
fixed in https://github.com/getpopper/popper/pull/899
