### ISSUE TITLE
The container’s $PATH gets overwritten by the host system’s $PATH

### ISSUE THREAD

**Issue by wtraylor** [getpopper/popper#900]
As I explained in issue #898, the `docker` script installed by [install.sh](https://github.com/getpopper/popper/blob/master/install.sh) overwrites all environment variables in Popper’s docker container with the host system’s variables. While that is in general useful, the `$PATH` variable should not be overwritten. If the host system’s `$PATH` doesn’t include for instance `/bin`, then the Alpine-based container cannot find essential executables.

This is the current (4098bc3) `popper` script generated by `install.sh`:
```bash
#!/usr/bin/env sh

printenv > /tmp/.envfile

docker run --rm -ti \
  --volume /tmp:/tmp \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume "$PWD":"$PWD" \
  --workdir "$PWD" \
  --env-file /tmp/.envfile \
  getpopper/popper:v2.7.0 "$@"
```

My suggestion is to filter out the `$PATH` variable from `/tmp/.envfile`.

**Comment by ivotron** [comment]
thanks for looking into this @wtraylor. For running `popper` within the container, only `git` (which is invoked indirectly via GitPython) and the `popper` binary need to be reachable via `PATH`. So the script needs `/usr/bin` (for Git) and `/usr/local/bin` (for Popper). So one thing that could done is to override the `PATH` variable via an `--env` flag:

```bash
--env PATH="/usr/bin:/usr/local/bin"
```

and that would ensure that regardless of what's on the host, the container always works as it should. One corner case would be when a step explicitly defines the `PATH` variable as a secret, which is when this wouldn't work, although this would be weird for a workflow to attempt to do.

BTW, almost all unix systems (many linux distros, macos, cywgin, etc.) have `/bin` in the `PATH`, so I'm curious where do you found this was not the case, could you please provide more info about this environment? is that your machine? if it is, which OS do you use?

thanks!!

**Comment by wtraylor** [comment]
> BTW, almost all unix systems (many linux distros, macos, cywgin, etc.) have `/bin` in the `PATH`, so I'm curious where do you found this was not the case, could you please provide more info about this environment? is that your machine? if it is, which OS do you use?

Yes, you are right, @ivotron. `/bin` should be in the `PATH`. For some reason it is not on my Archlinux system. Weird, I cannot trace back where it got lost.

Anyway, the default Archlinux is correct:
```
$ docker run --rm archlinux printenv | grep PATH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

Sorry that this is an issue on my particular system only. Still I’d like to include the `--env` flag to cover even such rare corner cases. I will create a pull request.
