### ISSUE TITLE
cli: k8s: try scheduling the init pod on the master node at the very last 

### ISSUE THREAD

**Issue by JayjeetAtGithub** [getpopper/popper#927]
When no shared PersistentVolume is available, we try to schedule the init pod iteratively on all the nodes, and once a node accepts the init pod, we remember it and schedule all the subsequent steps pods there on that node so that all the pods can use a local volume on that node. Currently,  [while visiting each node iteratively](https://github.com/getpopper/popper/blob/01eadd5e54bd686291cef20bcb4e2fd3b493829f/src/popper/runner_kubernetes.py#L117), we start from the first node and most of the time it turns out to be the master node (labeled as master) and results in waste work trying to schedule on the master node. To prevent this wastage of time trying to schedule on master nodes, we can tweak the logic to find out the master nodes from the node list and push them to the end of the list, so that we start with visiting a non-master node and keep the masters as the last resort.

**Comment by rishiUT** [comment]
Hi! I would like to work on this issue with a group of UT students, if that's alright.

**Comment by CarterB-UT** [comment]
Is this now closable?

**Comment by JayjeetAtGithub** [comment]
Done
